name: "Block Merges but Allow Vendor Updates"
description: "Prevent merging pull requests that contain merge commits unless they are from git vendor."
author: "Russell Bunch"
branding:
  icon: "alert-circle"
  color: "Red"

inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
